### ISSUE TITLE
Disable Google Font

### ISSUE THREAD

**Issue by SaeedSoltoon** [yithemes/yith-proteo#12]
Hi,
Great Theme & Thanks for the work.
How to disable google font, and add custom font by uploading corresponding font files in child theme?
Any help appreciated.

**Comment by francgrasso** [comment]
Hi there,
you can add this function in child theme

/**
 * Disable google font stylesheet
 *
 * @return void
 */
function yith_proteo_customer_remove_google_fonts() {
 wp_dequeue_style( 'yith-proteo-google-font' );
 wp_dequeue_style( 'yith-proteo-custom-google-fonts' );
}
add_action( 'wp_enqueue_scripts', 'yith_proteo_customer_remove_google_fonts', 100 );

This will remove the inclusion of google font stylesheets.

If you want to remove also the custom css added to set the font for each selector involved, you may add this function too:

/**
 * Disable google font custom css
 *
 * @return void
 */
function yith_proteo_massive_google_font_enqueue(){
 return;
}

But please, wait for the coming Proteo version 1.4.2 because we are making this function pluggable. Adding this function in your current version of proteo (1.4.1 and below) will cause a fatal error because of function already declared.

**Comment by francgrasso** [comment]
Since no news, I'm closing this issue
