### ISSUE TITLE
Elementor pro adding to cart issue

### ISSUE THREAD

**Issue by JSamonig** [yithemes/yith-proteo#14]
Hi!

Great theme! I am experiencing some issues with Yith Proteo on my [website](https://www.neonstrike.com/). When I add a product to the cart, the header breaks. I think this is due to Elementor pro, as when it is deactivated the issue goes away. The installed plugins are:

Advanced Product Fields for WooCommerce
All-in-One WP Migration
Async JavaScript
Autoptimize
Breadcrumb NavXT
CartFlows
Contact Form 7
EditorsKit
GDPR Cookie Consent
Elementor
Elementor - Header, Footer & Blocks
Elementor Pro
Hostinger
Insert Headers and Footers
Mailchimp for WooCommerce
MC4WP: Mailchimp for WordPress
Site Kit by Google
Starter Templates
Stripe For WooCommerce
WebARX
Webcraftic Robin image optimizer
WooCommerce
WooCommerce Cart Abandonment Recovery
WooCommerce PayPal Checkout Gateway
WPForms Lite
YITH Proteo Toolkit
YITH Slider for page builders
YITH WooCommerce Product Slider Carousel
YITH WooCommerce Wishlist
Yoast SEO

WP version: 5.6
PHP version: 7.2.34

An image is attached:
![image](https://user-images.githubusercontent.com/44686851/104049363-c550e480-51dc-11eb-9835-f82cdd08fafa.png)

kind regards,
Jakob

**Comment by francgrasso** [comment]
Hi there, 
I think the issue is with the css behaviour on the cart widget. The list of products and actions should normally stay in display: none (or similar) and be visible while hovering the cart icon.
If you share with me a live link I can help you with a proper CSS to use :)

PS. At the moment your website link points to a different themed site
