### ISSUE TITLE
Disable source map

### ISSUE THREAD

**Issue by Mte90** [yithemes/yith-proteo#27]
The assets generated include the source map

**Comment by francgrasso** [comment]
Hi there,
the main purpose of this Github repository is to help the development of the theme, and a CSS MAP is very usefull during debug or edits. Since all scss files are provided you can thing to recompile them adding the --sourcemap=none clausole to the sass command. You can find the commands used to compile this package in the gruntfile.js file.
Please note that releases packages (zip) here on github and on wordpress.org are not including sourcemaps because the packages are meant to use in production environments, opposite of this.

**Comment by Mte90** [comment]
Can you add that instruction on the readme or a command to the gruntfile?

**Comment by francgrasso** [comment]
hei @Mte90 
I've added instruction in the README.md file
